events {
    worker_connections 1024;
}

http {
    set_real_ip_from  172.16.0.0/12;
    set_real_ip_from  192.168.0.0/16;
    set_real_ip_from  127.0.0.1;
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;

    server {
        listen 80;

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;

            # Логика цепочки:
            # Если мы на nginx1 -> идем на nginx2
            # Если мы на nginx2 -> идем на nginx3
            # Если мы на nginx3 -> идем на app
            
            # Для простоты теста, давайте в docker-compose 
            # пробросим разные переменные или просто будем бить в порты.
            
            # СЕЙЧАС ДЛЯ ТЕСТА УКАЖЕМ ПРЯМО:
            proxy_pass http://nginx2; 
        }
    }
}
